# Generated by Django 2.1.5 on 2021-07-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]

